select * from customer limit 20;

--1. What is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

--2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
  and purchase_amount >= (select AVG(purchase_amount) from customer);

--3. Which are the top 5 products with the highest average review ratings?

select item_purchased, ROUND(AVG(review_rating), 2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--4. What is the average purchase amount by shipping type?

select shipping_type, ROUND(AVG(purchase_amount), 2) as avg_purchase_amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by avg_purchase_amount desc;

--5. How does spending compare between subscribers and non-subscribers?

select subscription_status,
       ROUND(AVG(purchase_amount), 2) as avg_purchase_amount,
       SUM(purchase_amount) as total_revenue,
       COUNT(*) as customer_count
from customer
group by subscription_status;

--6. Which products rely most heavily on discounts for their sales?

select item_purchased,
       COUNT(*) filter (where discount_applied = 'Yes') as discounted_sales,
       COUNT(*) as total_sales,
       ROUND(100.0 * COUNT(*) filter (where discount_applied = 'Yes') / COUNT(*), 2) as discount_dependency_pct
from customer
group by item_purchased
order by discount_dependency_pct desc
limit 5;

--7. How are customers segmented by loyalty based on their number of previous purchases?

select
    case
        when previous_purchases >= 11 then 'Loyal'
        when previous_purchases >= 2 then 'Returning'
        else 'New'
    end as loyalty_segment,
    COUNT(*) as customer_count
from customer
group by loyalty_segment
order by customer_count desc;

--8. What are the top-selling products by category?

select category, item_purchased, units_sold
from (
    select category, item_purchased,
           COUNT(*) as units_sold,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) as rn
    from customer
    group by category, item_purchased
) ranked
where rn <= 3
order by category, units_sold desc;

--9. Is there a relationship between repeat buyers and subscription status?

select subscription_status, COUNT(*) as repeat_buyer_count
from customer
where previous_purchases > 5
group by subscription_status;

--10. How much revenue does each age group contribute?

select age_group, SUM(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;
