select * from customer limit 20;

--1. What is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as revenue 
from customer
group by gender ;

--2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer 
where purchase_amount >= (select AVG(purchase_amount) from customer);

--3. Which are the top 5 products with the highest average review ratings?

select item_purchased, rounAVG(review_rating) as "Average Product Rating" 
from customer 
group by item_purchased
order by AVG(review_rating) desc 
limit 5;